[tool.ruff]
line-length = 120

# Exclude the following files and directories.
exclude = [
  ".git",
  ".hg",
  ".mypy_cache",
  ".tox",
  ".venv",
  "_build",
  "buck-out",
  "build",
  "dist",
  "env",
  "venv",
  "**/*.ipynb",  # Jupyter Notebook 파일 제외
  "*/prompt/*"
]

[tool.ruff.lint]
# Never enforce `E501` (line length violations).
extend-select = ["C901", "E501", "E402"]
select = ["C", "E", "F", "I", "W"]


[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "F811"]

[tool.ruff.lint.isort]
lines-after-imports = 2

# import 섹션 사이에 빈 줄 추가
lines-between-types = 1

# 섹션 순서 설정
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"