SEED: 456
data:
  train_path: ../data/train.csv
  test_path: ../data/test.csv
  output_dir: ../output
  test_size: 0.3
  max_length: 30
train:
  train_batch_size: 32
  eval_batch_size: 32
  lr: 2e-05
wandb:
  project: Data Centric
  entity: minseo
# 커밋시 절대 토큰을 추가하지 말 것. 향후 .env 파일로 분리하는 등 보안 개선 예정
huggingface:
  token:
  organization: paper-company
  repo_id: bert-base-pretrained
DEBUG : True