SEED: 456
data:
  train_name: train
  output_dir: ../output
  test_size: 0.3
  max_length: 30
train:
  train_batch_size: 32
  eval_batch_size: 32
  lr: 2e-05
wandb:
  project: Data Centric
  entity: minseo
huggingface:
  model_repo_id: bert-base-pretrained
DEBUG : True